In [1]:
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df=pd.read_csv("/kaggle/input/ibm-hr-analytics-attrition-dataset/WA_Fn-UseC_-HR-Employee-Attrition.csv")
df.head(5)

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1,...,1,80,0,8,0,1,6,4,0,5
1,49,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,1,2,...,4,80,1,10,3,3,10,7,1,7
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,1,4,...,2,80,0,7,3,3,0,0,0,0
3,33,No,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,1,5,...,3,80,0,8,3,3,8,7,3,0
4,27,No,Travel_Rarely,591,Research & Development,2,1,Medical,1,7,...,4,80,1,6,3,3,2,2,2,2

In [3]:
df.isnull().sum()

Age                         0
Attrition                   0
BusinessTravel              0
DailyRate                   0
Department                  0
DistanceFromHome            0
Education                   0
EducationField              0
EmployeeCount               0
EmployeeNumber              0
EnvironmentSatisfaction     0
Gender                      0
HourlyRate                  0
JobInvolvement              0
JobLevel                    0
JobRole                     0
JobSatisfaction             0
MaritalStatus               0
MonthlyIncome               0
MonthlyRate                 0
NumCompaniesWorked          0
Over18                      0
OverTime                    0
PercentSalaryHike           0
PerformanceRating           0
RelationshipSatisfaction    0
StandardHours               0
StockOptionLevel            0
TotalWorkingYears           0
TrainingTimesLastYear       0
WorkLifeBalance             0
YearsAtCompany              0
YearsInCurrentRole          0
YearsSinceLastPromotion     0
YearsWithCurrManager        0
dtype: int64

In [1]:
df.pairplot(data=df)
plt.show()

NameError: name 'df' is not defined

In [4]:
df["JobLevel"].value_counts()

JobLevel
1    543
2    534
3    218
4    106
5     69
Name: count, dtype: int64

In [5]:
df["Department"].unique()

array(['Sales', 'Research & Development', 'Human Resources'], dtype=object)

In [6]:
en_data=df[["Gender","MaritalStatus","Department","Attrition","OverTime"]]
en_data.head(2)

   Gender MaritalStatus              Department Attrition OverTime
0  Female        Single                   Sales       Yes      Yes
1    Male       Married  Research & Development        No       No

In [7]:
pd.get_dummies(en_data).info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1470 entries, 0 to 1469
Data columns (total 12 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   Gender_Female                      1470 non-null   bool
 1   Gender_Male                        1470 non-null   bool
 2   MaritalStatus_Divorced             1470 non-null   bool
 3   MaritalStatus_Married              1470 non-null   bool
 4   MaritalStatus_Single               1470 non-null   bool
 5   Department_Human Resources         1470 non-null   bool
 6   Department_Research & Development  1470 non-null   bool
 7   Department_Sales                   1470 non-null   bool
 8   Attrition_No                       1470 non-null   bool
 9   Attrition_Yes                      1470 non-null   bool
 10  OverTime_No                        1470 non-null   bool
 11  OverTime_Yes                       1470 non-null   bool
dtypes: bool(12)
memory usage: 17.4 KB

In [8]:
from sklearn.preprocessing import OneHotEncoder

In [9]:
ohe=OneHotEncoder(drop="first")
ar=ohe.fit_transform(en_data).toarray()

In [10]:
df_encoded=pd.DataFrame(ar,columns=["Gender_Male","MaritalStatus_Married","MaritalStatus_Single","Department_Research & Development","Department_Sales","Attrition_Yes","OverTime_Yes"])
df_encoded.head(2)

,Gender_Male,MaritalStatus_Married,MaritalStatus_Single,Department_Research & Development,Department_Sales,Attrition_Yes,OverTime_Yes
0,0.0,0.0,1.0,0.0,1.0,1.0,1.0
1,1.0,1.0,0.0,1.0,0.0,0.0,0.0

In [11]:
df_new=df.drop(["Gender","MaritalStatus","Department","Attrition","OverTime"],axis=1)

In [12]:
df1=pd.concat([df_new.reset_index(drop=True),df_encoded.reset_index(drop=True)],axis=1)
df1.head(1)

,Age,BusinessTravel,DailyRate,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,EnvironmentSatisfaction,HourlyRate,...,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager,Gender_Male,MaritalStatus_Married,MaritalStatus_Single,Department_Research & Development,Department_Sales,Attrition_Yes,OverTime_Yes
0,41,Travel_Rarely,1102,1,2,Life Sciences,1,1,2,94,...,4,0,5,0.0,0.0,1.0,0.0,1.0,1.0,1.0

In [13]:
x=df1[["Age","Gender_Male","MaritalStatus_Married","MaritalStatus_Single","Department_Research & Development","Department_Sales","DistanceFromHome","EnvironmentSatisfaction","JobSatisfaction","MonthlyIncome","OverTime_Yes","PercentSalaryHike","TotalWorkingYears","TrainingTimesLastYear","YearsAtCompany","YearsInCurrentRole","YearsSinceLastPromotion","YearsWithCurrManager","NumCompaniesWorked"]]
y=df1["Attrition_Yes"]

In [14]:
df1["Attrition_Yes"].value_counts()

Attrition_Yes
0.0    1233
1.0     237
Name: count, dtype: int64

In [15]:
from sklearn.model_selection import train_test_split

In [16]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=0)

In [17]:
from sklearn.linear_model import LogisticRegression

In [18]:
lor=LogisticRegression(class_weight="balanced")
lor.fit(x_train,y_train)

/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression(class_weight='balanced')

In [19]:
lor.score(x_test,y_test)*100

69.38775510204081

In [20]:
lor.predict([[41,0.0,0.0,1.0,0.0,1.0,1,2,4,1000,1.0,11,8,0,6,4,0,5,8]])

/usr/local/lib/python3.11/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(

array([1.])

In [21]:
import joblib
joblib.dump(lor, "my_model1.pk1")

['my_model1.pk1']

In [22]:
from sklearn.metrics import confusion_matrix

In [23]:
cf=confusion_matrix(y_test,lor.predict(x_test))
cf

array([[253, 118],
       [ 17,  53]])

In [24]:
en1_data=df[["Department","Gender","JobRole"]]

In [25]:
pd.get_dummies(en1_data).info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1470 entries, 0 to 1469
Data columns (total 14 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   Department_Human Resources         1470 non-null   bool
 1   Department_Research & Development  1470 non-null   bool
 2   Department_Sales                   1470 non-null   bool
 3   Gender_Female                      1470 non-null   bool
 4   Gender_Male                        1470 non-null   bool
 5   JobRole_Healthcare Representative  1470 non-null   bool
 6   JobRole_Human Resources            1470 non-null   bool
 7   JobRole_Laboratory Technician      1470 non-null   bool
 8   JobRole_Manager                    1470 non-null   bool
 9   JobRole_Manufacturing Director     1470 non-null   bool
 10  JobRole_Research Director          1470 non-null   bool
 11  JobRole_Research Scientist         1470 non-null   bool
 12  JobRole_Sales Executive            1470 non-null   bool
 13  JobRole_Sales Representative       1470 non-null   bool
dtypes: bool(14)
memory usage: 20.2 KB

In [26]:
ohe1=OneHotEncoder(drop="first")
ar1=ohe.fit_transform(en1_data).toarray()
ar1

array([[0., 1., 0., ..., 0., 1., 0.],
       [1., 0., 1., ..., 1., 0., 0.],
       [1., 0., 1., ..., 0., 0., 0.],
       ...,
       [1., 0., 1., ..., 0., 0., 0.],
       [0., 1., 1., ..., 0., 1., 0.],
       [1., 0., 1., ..., 0., 0., 0.]])

In [27]:
df_encoded1=pd.DataFrame(ar1,columns=["Department_Research & Developmen","Department_Sales","Gender_Male","JobRole_Human Resources","JobRole_Laboratory Technician","JobRole_Manager","JobRole_Manufacturing Director","JobRole_Research Director","JobRole_Research Scientist","JobRole_Sales Executive","JobRole_Sales Representative"])
df_encoded1

,Department_Research & Developmen,Department_Sales,Gender_Male,JobRole_Human Resources,JobRole_Laboratory Technician,JobRole_Manager,JobRole_Manufacturing Director,JobRole_Research Director,JobRole_Research Scientist,JobRole_Sales Executive,JobRole_Sales Representative
0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
2,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
3,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
4,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...
1465,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
1466,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1467,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
1468,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1469,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0

In [28]:
df_new1=df.drop(["Gender","Department","JobRole"],axis=1)
df_new1

,Age,Attrition,BusinessTravel,DailyRate,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,EnvironmentSatisfaction,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,1102,1,2,Life Sciences,1,1,2,...,1,80,0,8,0,1,6,4,0,5
1,49,No,Travel_Frequently,279,8,1,Life Sciences,1,2,3,...,4,80,1,10,3,3,10,7,1,7
2,37,Yes,Travel_Rarely,1373,2,2,Other,1,4,4,...,2,80,0,7,3,3,0,0,0,0
3,33,No,Travel_Frequently,1392,3,4,Life Sciences,1,5,4,...,3,80,0,8,3,3,8,7,3,0
4,27,No,Travel_Rarely,591,2,1,Medical,1,7,1,...,4,80,1,6,3,3,2,2,2,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1465,36,No,Travel_Frequently,884,23,2,Medical,1,2061,3,...,3,80,1,17,3,3,5,2,0,3
1466,39,No,Travel_Rarely,613,6,1,Medical,1,2062,4,...,1,80,1,9,5,3,7,7,1,7
1467,27,No,Travel_Rarely,155,4,3,Life Sciences,1,2064,2,...,2,80,1,6,0,3,6,2,0,3
1468,49,No,Travel_Frequently,1023,2,3,Medical,1,2065,4,...,4,80,0,17,3,2,9,6,0,8
1469,34,No,Travel_Rarely,628,8,3,Medical,1,2068,2,...,1,80,0,6,3,4,4,3,1,2

In [29]:
df2=pd.concat([df_new1.reset_index(drop=True),df_encoded1.reset_index(drop=True)],axis=1)
df2.head(1)

,Age,Attrition,BusinessTravel,DailyRate,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,EnvironmentSatisfaction,...,Department_Sales,Gender_Male,JobRole_Human Resources,JobRole_Laboratory Technician,JobRole_Manager,JobRole_Manufacturing Director,JobRole_Research Director,JobRole_Research Scientist,JobRole_Sales Executive,JobRole_Sales Representative
0,41,Yes,Travel_Rarely,1102,1,2,Life Sciences,1,1,2,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0

In [30]:
a=df2[["Gender_Male","Department_Research & Developmen","Department_Sales","JobRole_Human Resources","JobRole_Laboratory Technician","JobRole_Manager","JobRole_Manufacturing Director","JobRole_Research Director","JobRole_Research Scientist","JobRole_Sales Executive","JobRole_Sales Representative","JobLevel","TotalWorkingYears","YearsAtCompany","YearsInCurrentRole"]]
b=df2["MonthlyIncome"]

In [31]:
a_train,a_test,b_train,b_test=train_test_split(a,b,test_size=0.2,random_state=42)

In [32]:
from sklearn.linear_model import LinearRegression

In [33]:
lr=LinearRegression()
lr.fit(a_train,b_train)

LinearRegression()

In [34]:
lr.score(a_test,b_test)*100

93.70566184040254

In [35]:
# lr.predict()

In [36]:
import joblib
joblib.dump(lr,"salary_model1.pk1")

['salary_model1.pk1']